"""
solver.py  --  LAO* planner over prerequisite-DAG mastery states.

Current SSP formulation:
  - State key: frozenset(mastered_node_ids)
  - Terminal: target_lo_nodes is a subset of state
  - Action: any unmastered concept whose prerequisites are mastered
  - Collapsed cost: T_v / p(v, s)

The stochastic retry self-loop is collapsed into the geometric expected
mastery cost.  After this collapse every explicit transition is strict
progress, s -> s union {v}, so cost revision can be exact in one reverse
topological pass over the expanded mastery states.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, FrozenSet, List, Optional, Set, Tuple

import networkx as nx

from src.planner_engine.heuristics import max_heuristic, sum_heuristic
from src.planner_engine.zpd_utils import get_valid_actions


State = FrozenSet[int]


@dataclass
class ActionInfo:
    """Cached transition information for attempting one concept."""

    concept: int
    cost: float
    success_state: State


@dataclass
class StateNode:
    """One node in the explicit LAO* search graph."""

    state: State
    value: float
    best_action: Optional[int] = None
    actions: Dict[int, ActionInfo] = field(default_factory=dict)
    is_terminal: bool = False
    is_expanded: bool = False


@dataclass
class PlanResult:
    """Full LAO* output for analysis and experiment logging."""

    policy: Dict[State, int]
    values: Dict[State, float]
    expanded_count: int
    iterations: int
    converged: bool


class ExplicitGraph:
    """Explicit graph generated by LAO*."""

    def __init__(self) -> None:
        self.expanded: Dict[State, StateNode] = {}

    def get(self, state: State) -> Optional[StateNode]:
        return self.expanded.get(state)

    def __getitem__(self, state: State) -> StateNode:
        return self.expanded[state]

    def add(self, node: StateNode) -> StateNode:
        self.expanded[node.state] = node
        return node


class _OracleCostMixin:
    """Compatibility layer for both new OracleInterface and old predict_mc."""

    oracle: object
    edge_index: object
    num_nodes: int
    mc_samples: int
    default_base_cost: float
    _target_for_heuristic: State
    _query_cache: Dict[Tuple[int, State], Tuple[float, float]]
    _base_cost_cache: Dict[int, float]
    _best_case_prob_cache: Dict[int, float]

    def _state_to_mask(self, state: State) -> torch.Tensor:
        """Convert mastered-node set to a float mask [N]."""
        import torch

        mask = torch.zeros(self.num_nodes)
        for n in state:
            if 0 <= n < self.num_nodes:
                mask[n] = 1.0
        return mask

    def _zero_x(self) -> torch.Tensor:
        """Return a blank feature matrix [N, 2] (no history)."""
        import torch

        return torch.zeros(self.num_nodes, 2)

    @staticmethod
    def _as_float(value: object) -> float:
        if hasattr(value, "item"):
            return float(value.item())  # torch scalar / numpy scalar
        return float(value)  # type: ignore[arg-type]

    @staticmethod
    def _sanitize_probability(p: float) -> float:
        """Clamp tiny numerical violations while keeping invalid values visible."""
        if p <= 0.0:
            return 1e-12
        if p > 1.0:
            return 1.0
        return p

    def success_prob(self, v: int, mastered: State) -> float:
        """Return p(v, s), using the new OracleInterface when available."""
        if hasattr(self.oracle, "success_prob"):
            p = getattr(self.oracle, "success_prob")(v, mastered)
            return self._sanitize_probability(self._as_float(p))

        p, _ = self._query_oracle(v, mastered)
        return p

    def base_cost(self, v: int) -> float:
        """Return T_v, falling back to the configured default for legacy oracles."""
        if v in self._base_cost_cache:
            return self._base_cost_cache[v]

        if hasattr(self.oracle, "base_cost"):
            T = self._as_float(getattr(self.oracle, "base_cost")(v))
        else:
            T = self.default_base_cost

        if T <= 0.0:
            raise ValueError(f"base_cost({v}) must be positive, got {T}")

        self._base_cost_cache[v] = T
        return T

    def best_case_success_prob(self, v: int) -> float:
        """Return an admissible upper bound on p(v, s)."""
        if v in self._best_case_prob_cache:
            return self._best_case_prob_cache[v]

        if hasattr(self.oracle, "best_case_success_prob"):
            p = getattr(self.oracle, "best_case_success_prob")(v)
            p_star = self._sanitize_probability(self._as_float(p))
        else:
            # No monotonicity guarantee is implied by success_prob alone.
            p_star = 1.0

        self._best_case_prob_cache[v] = p_star
        return p_star

    def _query_oracle(self, v: int, state: State) -> Tuple[float, float]:
        """Return (p(v, s), T_v) with per-state caching."""
        key = (v, state)
        if key in self._query_cache:
            return self._query_cache[key]

        if hasattr(self.oracle, "success_prob"):
            p = self.success_prob(v, state)
            T = self.base_cost(v)
        elif hasattr(self.oracle, "predict_mc"):
            import torch

            x = self._zero_x()
            mask = self._state_to_mask(state)
            target = torch.tensor(v, dtype=torch.long)
            mean_p, _var_p, t_base = getattr(self.oracle, "predict_mc")(
                x,
                self.edge_index,
                target,
                mask,
                mc_samples=self.mc_samples,
            )
            p = self._sanitize_probability(self._as_float(mean_p))
            T = self._as_float(t_base)
            if T <= 0.0:
                T = self.default_base_cost
        else:
            raise TypeError(
                "Oracle must implement success_prob/base_cost or predict_mc"
            )

        self._query_cache[key] = (p, T)
        return p, T

    def _action_cost(self, action: int, state: State) -> float:
        """Geometric expected cost T_v / p(v, s)."""
        p, T = self._query_oracle(action, state)
        return T / p


class DAGPlanner(_OracleCostMixin):
    """LAO* planner on a prerequisite DAG.

    The constructor keeps the legacy DAGPlanner signature so existing
    experiment code can instantiate this class as a drop-in replacement.
    Use solve_result(...) to access the full LAO* PlanResult, or solve(...)
    for the historical (cost, path) pair.
    """

    def __init__(
        self,
        oracle,
        nx_graph: nx.DiGraph,
        config: dict,
        edge_index,
        num_nodes: int,
        max_iterations: int = 100000,
    ):
        assert nx.is_directed_acyclic_graph(nx_graph), \
            "Graph must be a DAG -- cycle detected!"

        self.oracle = oracle
        self.graph = nx_graph
        self.edge_index = edge_index
        self.num_nodes = num_nodes
        self.max_iterations = max_iterations

        self.concepts: List[int] = sorted(int(n) for n in nx_graph.nodes())
        self.mc_samples: int = config.get("oracle", {}).get("mc_samples", 20)
        self.default_base_cost: float = float(
            config.get("planner", {}).get(
                "base_cost",
                config.get("oracle", {}).get("t_base", 60.0),
            )
        )
        self.heuristic_name: str = str(
            config.get("planner", {}).get("heuristic", "sum")
        ).lower()
        if self.heuristic_name not in {"sum", "max", "zero"}:
            raise ValueError(
                "planner.heuristic must be one of: sum, max, zero"
            )

        self.graph_explicit = ExplicitGraph()
        self._query_cache: Dict[Tuple[int, State], Tuple[float, float]] = {}
        self._base_cost_cache: Dict[int, float] = {}
        self._best_case_prob_cache: Dict[int, float] = {}
        self._target_for_heuristic: State = frozenset()
        self._last_result: Optional[PlanResult] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def solve_result(
        self,
        current_state: Set[int],
        target_lo_nodes: Set[int],
    ) -> PlanResult:
        """Run LAO* and return the full policy/value result."""
        s0 = frozenset(current_state)
        target = frozenset(target_lo_nodes)
        self._reset_search(target)

        self._ensure_state(s0, target)
        iterations = 0
        converged = False

        while iterations < self.max_iterations:
            iterations += 1
            solution_states = self._get_best_solution_graph(s0)
            tip = self._find_tip_in_solution_graph(solution_states)

            if tip is not None:
                self._expand_state(tip, target)
                self._exact_cost_revision()
                continue

            self._exact_cost_revision()
            solution_states = self._get_best_solution_graph(s0)
            tip = self._find_tip_in_solution_graph(solution_states)
            if tip is None:
                converged = True
                break

        policy = {
            s: node.best_action
            for s, node in self.graph_explicit.expanded.items()
            if node.best_action is not None
        }
        values = {
            s: node.value
            for s, node in self.graph_explicit.expanded.items()
        }

        result = PlanResult(
            policy=policy,
            values=values,
            expanded_count=sum(
                1 for node in self.graph_explicit.expanded.values()
                if node.is_expanded and not node.is_terminal
            ),
            iterations=iterations,
            converged=converged,
        )
        self._last_result = result
        return result

    def solve(
        self,
        current_state: Set[int],
        target_lo_nodes: Set[int],
    ) -> Tuple[float, List[int]]:
        """Find a minimum-cost learning path from the current state."""
        result = self.solve_result(current_state, target_lo_nodes)
        s0 = frozenset(current_state)
        target = frozenset(target_lo_nodes)
        return result.values.get(s0, float("inf")), self._extract_path(
            s0, target, result.policy
        )

    # ------------------------------------------------------------------
    # LAO* helpers
    # ------------------------------------------------------------------

    def _reset_search(self, target: State) -> None:
        self.graph_explicit = ExplicitGraph()
        self._query_cache.clear()
        self._base_cost_cache.clear()
        self._best_case_prob_cache.clear()
        self._target_for_heuristic = target
        self._last_result = None

    def _is_terminal(self, state: State, target: State) -> bool:
        return target <= state

    def _heuristic(self, state: State, target: State) -> float:
        if self._is_terminal(state, target):
            return 0.0
        if self.heuristic_name == "zero":
            return 0.0
        if self.heuristic_name == "max":
            return max_heuristic(state, target, self, self.graph)
        return sum_heuristic(state, target, self)

    def _ensure_state(self, state: State, target: State) -> StateNode:
        node = self.graph_explicit.get(state)
        if node is not None:
            return node

        is_terminal = self._is_terminal(state, target)
        value = 0.0 if is_terminal else self._heuristic(state, target)
        return self.graph_explicit.add(
            StateNode(
                state=state,
                value=value,
                is_terminal=is_terminal,
                is_expanded=is_terminal,
            )
        )

    def _expand_state(self, state: State, target: State) -> None:
        node = self._ensure_state(state, target)
        if node.is_expanded or node.is_terminal:
            return

        actions = get_valid_actions(self.graph, set(state))
        for action in actions:
            succ = frozenset(set(state) | {action})
            self._ensure_state(succ, target)
            node.actions[action] = ActionInfo(
                concept=action,
                cost=self._action_cost(action, state),
                success_state=succ,
            )

        node.is_expanded = True

    def _bellman_update(self, state: State) -> Tuple[float, Optional[int]]:
        node = self.graph_explicit[state]
        if node.is_terminal:
            return 0.0, None
        if not node.actions:
            return float("inf"), None

        best_val = float("inf")
        best_action: Optional[int] = None

        for action in sorted(node.actions):
            info = node.actions[action]
            succ_val = self.graph_explicit[info.success_state].value
            total = info.cost + succ_val
            if (
                total < best_val
                or (total == best_val and (
                    best_action is None or action < best_action
                ))
            ):
                best_val = total
                best_action = action

        return best_val, best_action

    def _exact_cost_revision(self) -> None:
        """One reverse-topological Bellman pass over expanded states."""
        states = [
            s for s, node in self.graph_explicit.expanded.items()
            if node.is_expanded and not node.is_terminal
        ]
        states.sort(key=lambda s: -len(s))

        for state in states:
            node = self.graph_explicit[state]
            node.value, node.best_action = self._bellman_update(state)

    def _get_best_solution_graph(self, s0: State) -> Set[State]:
        """Collect states reachable by following current best actions."""
        visited: Set[State] = set()
        stack: List[State] = [s0]

        while stack:
            state = stack.pop()
            if state in visited:
                continue
            visited.add(state)

            node = self.graph_explicit.get(state)
            if node is None or node.is_terminal:
                continue
            if node.best_action is None:
                continue

            succ = frozenset(set(state) | {node.best_action})
            stack.append(succ)

        return visited

    def _find_tip_in_solution_graph(
        self,
        solution_states: Set[State],
    ) -> Optional[State]:
        """Return an unexpanded nonterminal tip in the best solution graph."""
        for state in sorted(solution_states, key=lambda s: (len(s), tuple(s))):
            node = self.graph_explicit.get(state)
            if node is None:
                return state
            if not node.is_expanded and not node.is_terminal:
                return state
        return None

    @staticmethod
    def _extract_path(
        s0: State,
        target: State,
        policy: Dict[State, int],
    ) -> List[int]:
        path: List[int] = []
        state = s0
        seen: Set[State] = set()

        while not target <= state:
            if state in seen or state not in policy:
                break
            seen.add(state)
            action = policy[state]
            path.append(action)
            state = frozenset(set(state) | {action})

        return path


class DAGPlannerDP(_OracleCostMixin):
    """Exact memoized DP baseline using the current geometric cost model."""

    def __init__(
        self,
        oracle,
        nx_graph: nx.DiGraph,
        config: dict,
        edge_index,
        num_nodes: int,
    ):
        assert nx.is_directed_acyclic_graph(nx_graph), \
            "Graph must be a DAG -- cycle detected!"

        self.oracle = oracle
        self.graph = nx_graph
        self.edge_index = edge_index
        self.num_nodes = num_nodes
        self.mc_samples: int = config.get("oracle", {}).get("mc_samples", 20)
        self.default_base_cost: float = float(
            config.get("planner", {}).get(
                "base_cost",
                config.get("oracle", {}).get("t_base", 60.0),
            )
        )

        self.memo: Dict[State, Tuple[float, List[int]]] = {}
        self._query_cache: Dict[Tuple[int, State], Tuple[float, float]] = {}
        self._base_cost_cache: Dict[int, float] = {}
        self._best_case_prob_cache: Dict[int, float] = {}
        self._target_for_heuristic: State = frozenset()

    def solve(
        self,
        current_state: Set[int],
        target_lo_nodes: Set[int],
    ) -> Tuple[float, List[int]]:
        """Find an exact minimum-cost path by exhaustive memoized DP."""
        self.memo.clear()
        self._query_cache.clear()
        self._target_for_heuristic = frozenset(target_lo_nodes)
        return self._dp(frozenset(current_state), frozenset(target_lo_nodes))

    def _dp(self, state: State, target: State) -> Tuple[float, List[int]]:
        if target <= state:
            return (0.0, [])
        if state in self.memo:
            return self.memo[state]

        actions = get_valid_actions(self.graph, set(state))
        if not actions:
            result: Tuple[float, List[int]] = (float("inf"), [])
            self.memo[state] = result
            return result

        best_cost = float("inf")
        best_path: List[int] = []

        for action in actions:
            next_state = frozenset(set(state) | {action})
            future_cost, future_path = self._dp(next_state, target)
            total = self._action_cost(action, state) + future_cost

            if (
                total < best_cost
                or (
                    total == best_cost
                    and (not best_path or action < best_path[0])
                )
            ):
                best_cost = total
                best_path = [action] + future_path

        self.memo[state] = (best_cost, best_path)
        return self.memo[state]
